// src/controllers/departmentController.js
// Department management controller with best practices
// - Uses asyncHandler to eliminate try-catch boilerplate
// - Proper error handling and validation
// - Resource count tracking

import Department from "../models/Department.js";
import Resource from "../models/Resource.js";
import mongoose from "mongoose";
import asyncHandler from "../middleware/asyncHandler.js";

// ============================================
// @desc    Create a new department
// @route   POST /api/departments
// @access  Private/Admin
// ============================================
export const createDepartment = asyncHandler(async (req, res) => {
  const { name, slug, description, icon, color } = req.body;

  if (!name?.trim()) {
    res.status(400);
    throw new Error("Department name is required");
  }

  // Check if department with same name or slug already exists
  const existingDept = await Department.findOne({
    $or: [
      { name: name.trim() },
      { slug: slug ? slug.trim().toLowerCase() : name.toLowerCase() },
    ],
  });

  if (existingDept) {
    res.status(400);
    throw new Error("Department with this name already exists");
  }

  // Create department (slug will be auto-generated by pre-save hook if not provided)
  const department = await Department.create({
    name: name.trim(),
    slug: slug ? slug.trim().toLowerCase() : undefined,
    description: description?.trim() || "",
    icon: icon || "📁",
    color: color || "#3B82F6",
  });

  res.status(201).json({
    success: true,
    message: "Department created successfully",
    data: department,
  });
});

// ============================================
// @desc    Get all departments
// @route   GET /api/departments?search=...&isActive=true
// @access  Public
// ============================================
export const getDepartments = asyncHandler(async (req, res) => {
  const { search, isActive } = req.query;

  // Build query
  const query = {};

  if (isActive !== undefined) {
    query.isActive = isActive === "true" || isActive === true;
  }

  // Text search on name and description
  if (search) {
    query.$text = { $search: search };
  }

  const departments = await Department.find(query).sort({ name: 1 });

  res.status(200).json({
    success: true,
    count: departments.length,
    data: departments,
  });
});

// ============================================
// @desc    Get single department by ID or slug
// @route   GET /api/departments/:id
// @access  Public
// ============================================
export const getDepartment = asyncHandler(async (req, res) => {
  const { id } = req.params;
  let department;

  // Try to find by ObjectId first, then by slug
  if (mongoose.Types.ObjectId.isValid(id)) {
    department = await Department.findById(id);
  } else {
    department = await Department.findOne({ slug: id });
  }

  if (!department || !department.isActive) {
    res.status(404);
    throw new Error("Department not found");
  }

  // Update resource count
  const resourceCount = await Resource.countDocuments({
    department: department._id,
    isActive: true,
  });

  department.resourceCount = resourceCount;
  await department.save();

  res.status(200).json({
    success: true,
    data: department,
  });
});

// ============================================
// @desc    Update department
// @route   PUT /api/departments/:id
// @access  Private/Admin
// ============================================
export const updateDepartment = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const { name, slug, description, icon, color } = req.body;

  const department = await Department.findById(id);

  if (!department) {
    res.status(404);
    throw new Error("Department not found");
  }

  // Check if new name/slug conflicts with existing department
  if (name || slug) {
    const conflictQuery = { _id: { $ne: id } };
    if (name) conflictQuery.name = name.trim();
    if (slug) conflictQuery.slug = slug.trim().toLowerCase();

    const existingDept = await Department.findOne(conflictQuery);
    if (existingDept) {
      res.status(400);
      throw new Error("Department with this name or slug already exists");
    }
  }

  // Update fields
  if (name) department.name = name.trim();
  if (slug) department.slug = slug.trim().toLowerCase();
  if (description !== undefined) department.description = description.trim();
  if (icon) department.icon = icon;
  if (color) department.color = color;

  await department.save();

  res.status(200).json({
    success: true,
    message: "Department updated successfully",
    data: department,
  });
});

// ============================================
// @desc    Delete department (soft delete)
// @route   DELETE /api/departments/:id
// @access  Private/Admin
// ============================================
export const deleteDepartment = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const department = await Department.findById(id);

  if (!department) {
    res.status(404);
    throw new Error("Department not found");
  }

  // Check if department has resources
  const resourceCount = await Resource.countDocuments({
    department: id,
    isActive: true,
  });

  if (resourceCount > 0) {
    res.status(400);
    throw new Error(
      `Cannot delete department with ${resourceCount} active resources. Please move or delete resources first.`
    );
  }

  // Soft delete
  department.isActive = false;
  await department.save();

  res.status(200).json({
    success: true,
    message: "Department deleted successfully",
  });
});

// ============================================
// @desc    Get department statistics
// @route   GET /api/departments/:id/stats
// @access  Public
// ============================================
export const getDepartmentStats = asyncHandler(async (req, res) => {
  const { id } = req.params;

  const department = await Department.findById(id);

  if (!department) {
    res.status(404);
    throw new Error("Department not found");
  }

  // Aggregate resource statistics for this department
  const stats = await Resource.aggregate([
    {
      $match: {
        department: new mongoose.Types.ObjectId(id),
        isActive: true,
      },
    },
    {
      $group: {
        _id: null,
        totalResources: { $sum: 1 },
        totalFiles: { $sum: { $cond: [{ $eq: ["$type", "file"] }, 1, 0] } },
        totalLinks: { $sum: { $cond: [{ $eq: ["$type", "link"] }, 1, 0] } },
        totalSize: { $sum: "$size" },
        totalViews: { $sum: "$views" },
        totalDownloads: { $sum: "$downloads" },
      },
    },
  ]);

  // Get most popular resources in this department
  const topResources = await Resource.find({
    department: id,
    isActive: true,
  })
    .sort({ views: -1 })
    .limit(5)
    .select("title type views downloads url");

  res.status(200).json({
    success: true,
    data: {
      department: {
        _id: department._id,
        name: department.name,
        slug: department.slug,
        icon: department.icon,
        color: department.color,
      },
      stats: stats[0] || {
        totalResources: 0,
        totalFiles: 0,
        totalLinks: 0,
        totalSize: 0,
        totalViews: 0,
        totalDownloads: 0,
      },
      topResources,
    },
  });
});
